version: '2'

services:
    composer:
        image: grpc_composer
        build: ./packages/Composer
        working_dir: ${WORKING_DIR}
        command: './run-for-all.sh install --prefer-dist --no-interaction'
        volumes:
            - ./packages/Composer:${WORKING_DIR}
            - ./:${CORE_DIR}

    php_client_generator:
        build: ./packages/PHPClientCompile/
        working_dir: ${WORKING_DIR}
        volumes:
            - ./packages/PHPClientCompile/:${WORKING_DIR}
            - ./:${CORE_DIR}