version: '2'
services:

    client:
        build: ./packages/Client
        working_dir: ${WORKING_DIR}
        volumes:
            - ./packages/Client:${WORKING_DIR}
            - ./:/core

    server:
        build: ./packages/Server
        working_dir: ${WORKING_DIR}
        command: 'rr-grpc serve -v -d'
        volumes:
            - ./packages/Server:${WORKING_DIR}
            - ./:/core

    php_contract:
        build: ./packages/PHPContract
        volumes:
            - ./packages/PHPContract:${WORKING_DIR}
            - ./:/core

    composer:
        image: ${COMPOSER_IMG}
        volumes:
            - ./:/core