<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace TimiTao\GRPC\Contract;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TimiTao.GRPC.Contract.SubtractReply</code>
 */
class SubtractReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 diff = 1;</code>
     */
    private $diff = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $diff
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 diff = 1;</code>
     * @return int
     */
    public function getDiff()
    {
        return $this->diff;
    }

    /**
     * Generated from protobuf field <code>int32 diff = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDiff($var)
    {
        GPBUtil::checkInt32($var);
        $this->diff = $var;

        return $this;
    }

}

